name: Deploy Node Backend to AWS

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Deploy on AWS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/insurance-backend

            echo "Pulling latest changes..."
            git fetch origin main
            git reset --hard origin/main

            echo "Building Docker image..."
            if docker-compose build; then
              echo "Restarting container..."
              docker-compose up -d
            else
              echo "âŒ Build failed! Keeping old container running."
            fi
          EOF
